config/routes.rb
Rails.application.routes.draw do
  default_url_options host: ENV["DOMAIN"]
  mount ActionCable.server => '/cable'

  # App Routes
  root to: 'dashboards#index'
  resources :dashboards,  except: [:new]
  resources :loops,       except: [:new, :edit]
  resources :connections, only:   [:show, :index, :create, :destroy], as: :integrations, controller: :integrations
  resources :glances,     except: [:new, :edit, :show, :index], as: :graphs, controller: :graphs
  resources :accounts,    except: [:edit]

  # Custom Routes and Actions
  patch '/dashboards/:id/duplicate'       => 'dashboards#duplicate',       as: :duplicate_dashboard
  patch '/dashboards/:id/reset-speakeasy' => 'dashboards#reset_speakeasy', as: :reset_dashboard_speakeasy
  patch '/loops/:id/reset-speakeasy'      => 'loops#reset_speakeasy',      as: :reset_loop_speakeasy
  patch '/glances/:id/reset-speakeasy'    => 'graphs#reset_speakeasy',     as: :reset_graph_speakeasy
  get   '/settings'                       => 'accounts#edit',              as: :settings
  get   '/billing'                        => 'accounts#billing',           as: :billing
  get   '/referral'                       => 'accounts#referral',          as: :referral
  post  '/stripe'                         => 'accounts#stripe'
  put   '/update-billing'                 => 'accounts#update_billing'
  get   '/signup(/:referrer_hash)'        => 'accounts#new',               as: :signup
  get   '/password'                       => 'accounts#password',          as: :password
  get   '/reset-password'                 => 'accounts#reset_password',    as: :reset_password
  post  '/password-auth'                  => 'accounts#password_auth'
  patch '/password-update'                => 'accounts#update_password'
  post  '/accounts'                       => 'accounts#create'
  get   '/login'                          => 'sessions#new',               as: :login
  post  '/login'                          => 'sessions#create'
  get   '/logout'                         => 'sessions#destroy',           as: :logout
  put   '/integrations/:id/autogenerate'  => 'integrations#autogenerate',  as: :autogenerate

  # Omniauth for Login
  get  'auth/:provider'          => 'sessions#create', as: :omniauth
  get  'auth/:provider/callback' => 'sessions#create'

  # Omniauth for Connections
  get  'integrations/:provider'          => 'integrations#create', as: :connection
  get  'integrations/:provider/callback' => 'integrations#create'

  # SpeakeasyLink Support
  get  '/board/:uuid' => 'dashboards#show',  as: :public_board
  get  '/loop/:uuid'  => 'loops#show',       as: :public_loop
  get  '/:uuid'       => 'graphs#edit',      as: :public_graph_form
  put  '/:uuid'       => 'graphs#update'

  # API and Webhook Routes
  namespace :api do
    namespace :zapier do
      resources :glances, only: [:index, :show], as: :graphs, controller: :graphs
      post 'glances/:id' => 'graphs#update'
    end
    namespace :hubspot do
      post :webhook, as: :graphs, controller: :graphs
    end
    namespace :google do
      post :webhook, as: :graphs, controller: :graphs
    end
  end
end

app/models/graph.rb
class Graph < ApplicationRecord
  acts_as_paranoid

  include Uuid
  include GraphOperation

  PROPERTY_STATUSES = %w(New Active Cancelled Contingent Pending Closed Reduced Withdrawn)
  SIZES = [['Tiny', 2], ['Small', 3], ['Medium', 6], ['Large', 9], ['Entire Dashboard', 12]]
  KINDS = %w(
    bombbomb_contacts-in-lists-pie-chart
    bombbomb_contacts-in-list-count
    bombbomb_contacts-in-list-graph-daily
    bombbomb_contacts-in-list-graph-weekly
    bombbomb_contacts-in-list-graph-monthly
    bombbomb_email-clicks-to-delivered-percent
    bombbomb_email-clicks-to-opens-percent
    bombbomb_email-plays-to-opens-percent
    bombbomb_email-plays-to-delivered-percent
    bombbomb_email-delivered-percent
    bombbomb_email-open-percent
    bombbomb_email-delivered-percent
    bombbomb_emails-sent-last-30-days
    bombbomb_emails-sent-last-60-days
    bombbomb_emails-sent-last-90-days
    facebook_number-of-fans
    facebook_number-of-new-fans-daily
    facebook_engaged-users-daily
    facebook_engaged-users-weekly
    facebook_engaged-users-monthly
    facebook_impressions-daily
    facebook_impressions-weekly
    facebook_impressions-monthly
    followupboss_calls-by-day
    followupboss_calls-by-week
    followupboss_calls-by-month
    followupboss_people-by-day
    followupboss_people-by-week
    followupboss_people-by-month
    followupboss_people-count
    followupboss_people-lead-count
    followupboss_people-contact-count
    followupboss_people-hot-prospect-count
    followupboss_people-nurture-count
    followupboss_people-buyer-count
    followupboss_people-seller-count
    followupboss_people-pending-count
    followupboss_people-closed-count
    followupboss_people-past-client-count
    followupboss_people-sphere-count
    followupboss_people-trash-count
    followupboss_people-lifecycle-pie
    google_bar
    google_currency
    google_donut
    google_line
    google_list
    google_number
    google_pie
    hubspot_lifecycle-pie-chart
    hubspot_subscriber-count
    hubspot_lead-count
    hubspot_mql-count
    hubspot_sql-count
    hubspot_opportunity-count
    hubspot_customer-count
    hubspot_evangelist-count
    hubspot_new-contacts-by-day
    hubspot_new-contacts-by-week
    hubspot_new-contacts-by-month
    hubspot_list-newest-contacts
    native_bar
    native_currency
    native_donut
    native_image
    native_line
    native_list
    native_number
    native_paragraph
    native_pie
    native_title
    zapier_currency
    zapier_number
    zapier_paragraph
    zapier_title
  )

  belongs_to :dashboard, touch: true, counter_cache: true
  belongs_to :integration, optional: true
  has_one :account, through: :dashboard

  validates :size, :title, :kind, presence: true
  validates :size, inclusion: { in: SIZES.map{|m| m[1] }, message: 'not a valid size' }
  validates :title, length: { maximum: 256 }

  before_validation :copy_title, if: 'self.kind == "native_title"'
  after_update :reset_error

  scope :valid, -> { where("error_count <= 10") }

  def self.with_connection(connection)
    KINDS.select{|k| k.include?(connection) }
  end

  def self.kinds_as_object
    kinds = {}
    Integration::PROVIDERS.each do |provider|
      kinds[provider[:provider].split('_').first] = []
    end
    KINDS.each{|k| kinds[k.split('_').first] << k.split('_').last }
    kinds
  end

  private

  def reset_error
    if self.errored_out?
      self.update_columns(error_count: 0, error_msg: '')
    end
  end

  def copy_title
    self.data = { value: self.title, output: 'title' }
  end
end

app/controllers/api/google/graphs_controller.rb
class Api::Google::GraphsController < ActionController::Base

  def webhook
    UpdateGraphsWorker.perform_async(request.env['HTTP_X_GOOG_CHANNEL_ID'])
    head :ok
  end

end

app/controllers/api/hubspot/graphs_controller.rb
class Api::Hubspot::GraphsController < ActionController::Base

  def webhook
    portals = params['_json']
    portals.each do |portal|
      id = Integration.where("integrations.auth->>'portal_id' = '?'", portal['portalId']).pluck(:id).first
      UpdateGraphsWorker.perform_async(id) unless id.nil?
    end
    head :ok
  end

end

app/controllers/api/zapier/graphs_controller.rb
# Zapier API supports these graph types:
# - Number
# - Title
# - Paragraph
# - Currency

class Api::Zapier::GraphsController < Api::ApiController
  before_action :set_graph, except: [:index]

  # Test action, enable integration when triggered.
  def index
    i = @current_account.integrations.where(provider: 'zapier_integration').first
    i.update_columns(enabled: true)
    head :ok
  end

  def show
    render json: @graph, serializer: GraphSerializer
  end

  def update
    @graph.update(graph_params) ?
      (head :ok) :
      (render json: @graph.errors, status: :unprocessable_entity)
  end

  private

  def set_graph
    @graph = @current_account.graphs.where("graphs.data->>'zapier_id' = ?", params[:id])
  end

  def graph_params
    params.require(:graph).permit(
      :title,
      data: [:value, :title, labels: [], series: []]
    )
  end
end

app/controllers/graphs_controller.rb
class GraphsController < ApplicationController
  before_action :set_graph, only: [:edit, :update, :destroy, :reset_speakeasy]
  before_action :authorize, only: [:create, :destroy, :reset_speakeasy]

  def create
    @graph = Graph.new(graph_params)
    # Don't redirect when pre-creating a zapier glance.
    dont_redirect = params[:dont_redirect].present? and params[:dont_redirect]
    if @graph.save
      dont_redirect ?
        (render json: @graph.reload.to_json) :
        (redirect_to edit_dashboard_path(@graph.dashboard), notice: 'Glance was successfully created.')
    else
      render json: @graph.errors, status: :unprocessable_entity
    end
  end

  def edit
    if allowed?
      @public_form = true
    else
      redirect_to login_path, notice: 'You must login to update this glance.'
    end
  end

  def update
    if allowed?
      if current_account.present? or verify_recaptcha(model: @graph)
        @graph.update(graph_params) ?
          (redirect_back(fallback_location: public_graph_form_path(@graph), notice: 'Glance was successfully updated.')) :
          (render json: @graph.errors, status: :unprocessable_entity)
      else
        render json: @graph.errors, status: :unprocessable_entity
      end
    else
      redirect_to login_path, notice: 'You must login to update this glance.'
    end
  end

  def reset_speakeasy
    @graph.regenerate_uuid!
    render json: { link: public_graph_form_url(@graph.reload.uuid), speakeasy: true }.to_json
  end

  def destroy
    dashboard = @graph.dashboard
    @graph.destroy
    redirect_to edit_dashboard_path(dashboard), notice: 'Glance was successfully destroyed.'
  end

  private

  def allowed?
    @graph.public_form? or current_account == @graph.account
  end

  def set_graph
    @graph = Graph.where("id = ? OR uuid = ?", params[:id], params[:uuid]).first
    @current_account = @graph.account if current_account.nil?
  end

  def graph_params
    # Hashify JSON encoded string from hidden field.
    params[:graph][:data] = ActiveSupport::JSON.decode(params[:graph][:data]) if params[:graph][:data].present?
    params.require(:graph).permit(
      :title,
      :size,
      :public_form,
      :kind,
      :dashboard_id,
      :integration_id,
      data: [
        :value, :src, :iso_code, :sheet_name, :range, :sheet_id, :range_labels, :page_id, :output, :zapier_id,
        labels: [], series: [],
        listings: [:address, :note, :status]
      ]
    )
  end
end

app/views/graphs/_edit.html.haml
- cache [ApplicationHelper::APP_VERSION, graph] do
  .modal.graph.modal-fixed-footer{ id: "edit-graph-modal-#{graph.id}" }
    = form_for graph, remote: true, html: { autocomplete: :off } do |f|
      = f.hidden_field :data, id: "edit-glance-#{graph.id}", value: f.object.data.to_json
      .modal-content
        .row
          .col.s12
            %h4
              = "Edit #{graph.output.capitalize} Glance"
              %a{ href: 'https://agentecho.zendesk.com/hc/en-us/articles/226553747-Creating-Editing-A-Glance', target: '_blank', class: 'white-text' }
                %small.right.btn-floating.center-align
                  ?
            = render partial: 'partials/errors'
        - if graph.errored_out?
          .row
            .col.s12
              %span
                %i.material-icons.red-text error_outline
                This glance has not been updating due to this error:
                %strong= graph.error_msg
        .row
          .col.m6.s12.no-gutter
            .input-field.col.s8
              = f.text_field :title
              = f.label :title
            .input-field.col.s4
              = f.select :size, Graph::SIZES, {}, { class: 'browser-default' }
        - if graph.kind != 'native_title'
          .row
            = react_component 'GlanceEdit', glance: graph
      .modal-footer
        = f.submit 'Update', class: 'btn col s6'
        .btn-flat.modal-action.modal-close.col.s6.center-align Cancel

app/views/graphs/_new.html.haml
.modal.graph.modal-fixed-footer#new-graph-modal
  = form_for @graph, remote: true, html: { autocomplete: :off } do |f|
    = f.hidden_field :dashboard_id
    = f.hidden_field :data, id: 'new-glance'
    = f.hidden_field :kind, id: 'new-glance-kind'
    = f.hidden_field :integration_id, id: 'new-glance-integration'
    .modal-content
      .row
        .col.s12
          %h4
            Add Glance
            %a{ href: 'https://agentecho.zendesk.com/hc/en-us/articles/226553747-Creating-Editing-A-Glance', target: '_blank', class: 'white-text' }
              %small.right.btn-floating.center-align
                ?
          = render partial: 'partials/errors'
      .row
        = react_component 'GlanceNew', integrations: Hash[@integrations.map{|i| [i.id, i.provider.split('_').first] }], kinds: Graph.kinds_as_object
      .row
        .col.m6.s12.no-gutter
          .input-field.col.s8
            = f.text_field :title
            = f.label :title
          .input-field.col.s4
            = f.select :size, Graph::SIZES, { include_blank: 'Size' }, { class: 'browser-default' }
    .modal-footer
      = f.submit 'Create', class: 'btn col s6'
      .btn-flat.modal-action.modal-close.col.s6.center-align Cancel

app/views/graphs/_speakeasy.html.haml
.modal{ id: "speakeasy-graph-modal-#{graph.id}" }
  .modal-content
    .row
      .col.s12
        %h4.hide-on-small-only
          = "#{graph.title}"
          %a{ href: 'https://agentecho.zendesk.com/hc/en-us/articles/226551167-Enabling-Sharing-a-Speakeasy-Link', target: '_blank', class: 'white-text' }
            %small.right.btn-floating.center-align
              ?
          %small.right SpeakeasyLink™
        %h4.hide-on-med-and-up
          = "#{graph.title}"
          %a{ href: 'https://agentecho.zendesk.com/hc/en-us/articles/226551167-Enabling-Sharing-a-Speakeasy-Link', target: '_blank', class: 'white-text' }
            %small.right.btn-floating.center-align
              ?
      .col.s12
        %p This link allows anyone to update this glance's information.
      .input-field.col.s12.m8
        = text_field_tag :speakeasy, "#{root_url}#{graph.uuid}", disabled: true
      .input-field.col.s12.m2
        %a.waves-effect.waves-light.btn.col.s12.copy-link{ href: '#' }
          %i.material-icons.left content_copy
          Copy
      .input-field.col.s12.m2
        = link_to reset_graph_speakeasy_path(graph),
                    remote: true,
                    method: :patch,
                    class: 'waves-effect waves-light btn col s12 regenerate-link',
                    data: { confirm: 'Are you use sure you want a new link? Anyone with the current link will not be able to access the page.' } do
          %i.material-icons.left refresh
          New Link
  .modal-footer
    .btn-flat.modal-action.modal-close.col.s12.center-align Close

app/views/graphs/edit.html.haml
.col.m6.offset-m3
  = form_for @graph, remote: true, html: { autocomplete: :off } do |f|
    = f.hidden_field :data, id: "edit-glance-#{@graph.id}", value: f.object.data.to_json
    .row
      .col.s12
        %h4= "Edit #{@graph.title} • #{@graph.output.capitalize} Glance"
        %hr
        = render partial: 'partials/errors'
        = react_component 'GlanceEdit', glance: @graph, hideSpeakeasy: true
        - if current_account.nil?
          .row
            .col.s12
              = recaptcha_tags
    .row
      = f.submit 'Update Glance', class: 'btn col s12'