config/routes.rb
Rails.application.routes.draw do
  default_url_options host: ENV["DOMAIN"]
  mount ActionCable.server => '/cable'

  # App Routes
  root to: 'dashboards#index'
  resources :dashboards,  except: [:new]
  resources :loops,       except: [:new, :edit]
  resources :connections, only:   [:show, :index, :create, :destroy], as: :integrations, controller: :integrations
  resources :glances,     except: [:new, :edit, :show, :index], as: :graphs, controller: :graphs
  resources :accounts,    except: [:edit]

  # Custom Routes and Actions
  patch '/dashboards/:id/duplicate'       => 'dashboards#duplicate',       as: :duplicate_dashboard
  patch '/dashboards/:id/reset-speakeasy' => 'dashboards#reset_speakeasy', as: :reset_dashboard_speakeasy
  patch '/loops/:id/reset-speakeasy'      => 'loops#reset_speakeasy',      as: :reset_loop_speakeasy
  patch '/glances/:id/reset-speakeasy'    => 'graphs#reset_speakeasy',     as: :reset_graph_speakeasy
  get   '/settings'                       => 'accounts#edit',              as: :settings
  get   '/billing'                        => 'accounts#billing',           as: :billing
  get   '/referral'                       => 'accounts#referral',          as: :referral
  post  '/stripe'                         => 'accounts#stripe'
  put   '/update-billing'                 => 'accounts#update_billing'
  get   '/signup(/:referrer_hash)'        => 'accounts#new',               as: :signup
  get   '/password'                       => 'accounts#password',          as: :password
  get   '/reset-password'                 => 'accounts#reset_password',    as: :reset_password
  post  '/password-auth'                  => 'accounts#password_auth'
  patch '/password-update'                => 'accounts#update_password'
  post  '/accounts'                       => 'accounts#create'
  get   '/login'                          => 'sessions#new',               as: :login
  post  '/login'                          => 'sessions#create'
  get   '/logout'                         => 'sessions#destroy',           as: :logout
  put   '/integrations/:id/autogenerate'  => 'integrations#autogenerate',  as: :autogenerate

  # Omniauth for Login
  get  'auth/:provider'          => 'sessions#create', as: :omniauth
  get  'auth/:provider/callback' => 'sessions#create'

  # Omniauth for Connections
  get  'integrations/:provider'          => 'integrations#create', as: :connection
  get  'integrations/:provider/callback' => 'integrations#create'

  # SpeakeasyLink Support
  get  '/board/:uuid' => 'dashboards#show',  as: :public_board
  get  '/loop/:uuid'  => 'loops#show',       as: :public_loop
  get  '/:uuid'       => 'graphs#edit',      as: :public_graph_form
  put  '/:uuid'       => 'graphs#update'

  # API and Webhook Routes
  namespace :api do
    namespace :zapier do
      resources :glances, only: [:index, :show], as: :graphs, controller: :graphs
      post 'glances/:id' => 'graphs#update'
    end
    namespace :hubspot do
      post :webhook, as: :graphs, controller: :graphs
    end
    namespace :google do
      post :webhook, as: :graphs, controller: :graphs
    end
  end
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
  acts_as_paranoid

  include Uuid
  include DashboardOperation

  belongs_to :account, touch: true
  has_many :graphs, dependent: :destroy

  validates :name, presence: true, length: { maximum: 256 }

  after_create :add_title_graph
  after_touch  :update_client_dashboard
  after_update :update_client_dashboard

  def loop_object
    return true
  end

  private

  def add_title_graph
    default_graph = Graph.new(
      dashboard: self,
      kind: 'native_title',
      title: self.name,
      data: { value: self.name, output: 'title' },
      size: 3
    )
    default_graph.save!
  end

  def update_client_dashboard
    DashboardBroadcast.perform_in(1.second, self.uuid)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :set_dashboard, only: [:show, :edit, :reset_speakeasy, :update, :duplicate, :destroy]
  before_action :authorize, only: [:show], unless: '@dashboard.public_form?'
  before_action :authorize, only: [:index, :new, :create, :edit, :reset_speakeasy, :update, :destroy]

  def index
    @title      = 'Boards'
    @dashboard  = Dashboard.new
    @dashboards = current_account.dashboards.order(:created_at)
    @loop       = Loop.new
    @loops      = current_account.loops.order(:created_at)
  end

  def show
    if params[:uuid].present?
      if current_account.present? or @dashboard.public_form?
        @graphs  = @dashboard.graphs_position_order
        @title   = "#{@dashboard.name} Board"
        @preview = params[:preview]
        @dashboard.account.points! if current_account.nil?
        render layout: 'dashboard'
      else
        redirect_to login_path, notice: 'You must login to access this board.'
      end
    else
      redirect_to public_board_path(@dashboard.uuid, preview: params[:preview])
    end
  end

  def edit
    @title = "Edit #{@dashboard.name} Board"
    @graphs = @dashboard.graphs_position_order
    @graph = Graph.new(dashboard: @dashboard)
  end

  def create
    @dashboard = Dashboard.new(dashboard_params)
    @dashboard.account = current_account
    @dashboard.save ?
      (redirect_to edit_dashboard_path(@dashboard), notice: 'Dashboard was successfully created.') :
      (render json: @dashboard.errors, status: :unprocessable_entity)
  end

  def duplicate
    @dashboard.duplicate!(dashboard_params[:name]) ?
      (redirect_back(fallback_location: dashboards_path, notice: 'Dashboard was successfully duplicated.')) :
      (render json: @dashboard.errors, status: :unprocessable_entity)
  end

  def reset_speakeasy
    @dashboard.disable_open_boards!
    @dashboard.regenerate_uuid!
    @dashboard.touch
    render json: { link: public_board_url(@dashboard.reload.uuid), speakeasy: true }.to_json
  end

  def update
    @dashboard.update(dashboard_params) ?
      (redirect_to edit_dashboard_path(@dashboard), notice: 'Dashboard was successfully updated.') :
      (render json: @dashboard.errors, status: :unprocessable_entity)
  end

  def destroy
    @dashboard.destroy
    redirect_to root_path, notice: 'Dashboard was successfully deleted.'
  end

  private

  def set_dashboard
    if params[:id].present?
      @dashboard = current_account.dashboards.find(params[:id])
    else
      @dashboard = Dashboard.find_by_uuid(params[:uuid])
    end
    render_404 if @dashboard.nil?
    @current_account = @dashboard.account if current_account.nil?
    @integrations = @current_account.integrations.is_enabled
  end

  def dashboard_params
    params.require(:dashboard).permit(:name, :public_form, positions: [])
  end
end

app/views/dashboards/_dashboard.html.haml
= react_component 'GlanceShow', { glances: dashboard.graphs_position_order.map(&:dashboard_data) }, { class: "dashboard-#{dashboard.uuid}" }

app/views/dashboards/_duplicate.html.haml
- cache [ApplicationHelper::APP_VERSION, dashboard] do
  .modal{ id: "duplicate-dashboard-modal-#{dashboard.id}" }
    = form_for dashboard, url: { action: :duplicate, id: dashboard.id }, remote: true, html: { autocomplete: :off } do |f|
      .modal-content
        %h4= "Duplicate #{dashboard.name} Board"
        = render partial: 'partials/errors'
        .input-field
          = f.text_field :name, value: ''
          = f.label :name, 'New Board Name'
        .input-field
          %p Do you want to enable this board's SpeakeasyLink™?
          = f.check_box :public_form, id: "public_form-#{dashboard.id}"
          = f.label :public_form, 'Enable', for: "public_form-#{dashboard.id}", class: 'public_form-label'
      .modal-footer
        = f.submit 'Duplicate', class: 'btn col s6'
        .btn-flat.modal-action.modal-close.col.s6.center-align Cancel

app/views/dashboards/_edit.html.haml
- cache [ApplicationHelper::APP_VERSION, dashboard] do
  .modal{ id: "edit-dashboard-modal-#{dashboard.id}" }
    = form_for dashboard, remote: true, html: { autocomplete: :off } do |f|
      .modal-content
        %h4
          = "Edit #{dashboard.name} Board"
          %a{ href: 'https://agentecho.zendesk.com/hc/en-us/articles/226551267-Creating-Editing-A-Board', target: '_blank', class: 'white-text' }
            %small.right.btn-floating.center-align
              ?
        = render partial: 'partials/errors'
        .input-field
          = f.text_field :name
          = f.label :name
        .input-field
          %p Do you want to enable this board's SpeakeasyLink™?
          = f.check_box :public_form, id: "public_form-#{dashboard.id}"
          = f.label :public_form, 'Enable', for: "public_form-#{dashboard.id}", class: 'public_form-label'
      .modal-footer
        = f.submit 'Update', class: 'btn col s6'
        .btn-flat.modal-action.modal-close.col.s6.center-align Cancel

app/views/dashboards/_new.html.haml
- cache ApplicationHelper::APP_VERSION do
  .modal{ id: "new-dashboard-modal" }
    = form_for dashboard, remote: true, html: { autocomplete: :off } do |f|
      .modal-content
        %h4
          New Board
          %a{ href: 'https://agentecho.zendesk.com/hc/en-us/articles/226551267-Creating-Editing-A-Board', target: '_blank', class: 'white-text' }
            %small.right.btn-floating.center-align
              ?
        = render partial: 'partials/errors'
        .row
          .input-field
            = f.text_field :name
            = f.label :name
          .input-field
            %p Do you want to enable this board's SpeakeasyLink™?
            = f.check_box :public_form
            = f.label :public_form, 'Enable', class: 'public_form-label'
      .modal-footer
        = f.submit 'Create', class: 'btn col s6'
        .btn-flat.modal-action.modal-close.col.s6.center-align Cancel

app/views/dashboards/_speakeasy.html.haml
.modal{ id: "speakeasy-dashboard-modal-#{dashboard.id}" }
  .modal-content
    .row
      .col.s12
        %h4.hide-on-small-only
          = "#{dashboard.name} Board"
          %small.right SpeakeasyLink™
        %h4.hide-on-med-and-up
          = "#{dashboard.name} Board"
          %br
          SpeakeasyLink™
      .col.s12
        %p This link allows anyone to view this dashboard.
      .input-field.col.s12.m8
        = text_field_tag :speakeasy, "#{root_url}board/#{dashboard.uuid}", disabled: true
      .input-field.col.s12.m2
        %a.waves-effect.waves-light.btn.copy-link.col.s12{ href: '#' }
          %i.material-icons.left content_copy
          Copy
      .input-field.col.s12.m2
        = link_to reset_dashboard_speakeasy_path(dashboard),
                    remote: true,
                    method: :patch,
                    class: 'waves-effect waves-light btn col s12 regenerate-link',
                    data: { confirm: 'Are you use sure you want a new link? Anyone with the current link will not be able to access the page.' } do
          %i.material-icons.left refresh
          New Link
  .modal-footer
    .btn-flat.modal-action.modal-close.col.s12.center-align Close

app/views/dashboards/edit.html.haml
.row
  .col.s9
    %h4
      = "#{@dashboard.name} Board"
  .col.s3.right-align
    - if @dashboard.public_form?
      %a.modal-trigger{ href: "#speakeasy-dashboard-modal-#{@dashboard.id}" }
        %i.material-icons vpn_lock
    %a.modal-trigger{ href: "#edit-dashboard-modal-#{@dashboard.id}" }
      .material-icons edit
    = link_to public_board_path(uuid: @dashboard.uuid), target: :blank do
      .material-icons open_in_new
  .col.s12
    %hr
.row
  .col.s12
    %h4
      Glances
      %small.right
        %a.btn-floating.small.modal-trigger{ href: "#new-graph-modal" }
          %i.material-icons add
- cache [ApplicationHelper::APP_VERSION, @graphs] do
  .row
    .col.s12
      %ul.collection.sortable.dashboard-graphs{ data: { id: @dashboard.id } }
        - @graphs.each do |graph|
          %li.collection-item{ data: { id: graph.id } }
            %a{ href: "#" }
              %i.grip.material-icons.grey-text reorder
            %span.hide-on-small-only
              = image_tag "/#{graph.integration_kind}-badge.png", class: 'brand-badge'
              = "#{graph.title} • #{graph.output.capitalize} Glance"
            %span.hide-on-med-and-up
              = "#{graph.title}"
            - if graph.errored_out?
              %span
                %i.material-icons.red-text error_outline
            .secondary-content
              - if graph.public_form?
                %a.modal-trigger{ href: "#speakeasy-graph-modal-#{graph.id}" }
                  %i.material-icons vpn_lock
              %a.modal-trigger{ href: "#edit-graph-modal-#{graph.id}" }
                %i.green-text.material-icons edit
              = link_to graph, method: :delete, data: { confirm: 'Are you sure?' }, remote: true do
                %i.red-text.material-icons delete
= render 'graphs/new'
= render 'dashboards/edit', dashboard: @dashboard
= render 'dashboards/speakeasy', dashboard: @dashboard
- @dashboard.graphs.each do |graph|
  = render 'graphs/edit', graph: graph
  - if graph.public_form?
    = render 'graphs/speakeasy', graph: graph

app/views/dashboards/index.html.haml
.row
  .col.s12
    .right-align
      %a{ href: 'https://agentecho.zendesk.com/hc/en-us/articles/226545207-Getting-Started-with-AgentEcho', target: :blank }
        Getting Started
.row
  .col.s12.m12.l6
    - cache [ApplicationHelper::APP_VERSION, @dashboards] do
      .row
        .col.s12
          %h4
            Boards
            %small.right
              %a.btn-floating.small.modal-trigger{ :href => "#new-dashboard-modal" }
                %i.material-icons add
      .row
        .col.s12
          - if @dashboards.any?
            %ul.collection
              - @dashboards.each do |dashboard|
                - cache [ApplicationHelper::APP_VERSION, dashboard] do
                  %li.collection-item.avatar
                    %a{ href: public_board_path(dashboard.uuid), target: :blank }
                      %i.circle.material-icons.primary-color dashboard
                      %span.title= dashboard.name
                    %p.muted.hide-on-small-only
                      = "Updated: " + dashboard.updated_at.to_formatted_s(:long_ordinal)
                      %br
                      = pluralize(dashboard.graphs_count, 'glance')
                    .secondary-content
                      = link_to edit_dashboard_path(dashboard), class: 'green-text' do
                        %i.material-icons edit
                      = link_to dashboard_path(dashboard), method: :delete, class: 'red-text', data: { confirm: 'Are you sure?' } do
                        %i.material-icons delete
                      %a.modal-trigger{ :href => "#duplicate-dashboard-modal-#{dashboard.id}" }
                        %i.material-icons control_point_duplicate
                  = render 'duplicate', dashboard: dashboard
      = render 'new', dashboard: @dashboard
  .col.s12.m12.l6
    - cache [ApplicationHelper::APP_VERSION, @dashbaords, @loops] do
      .row
        .col.s12
          %h4
            Loops
            %small.right
              %a.btn-floating.small.modal-trigger{ href: "#new-loop-modal" }
                %i.material-icons add
      .row
        .col.s12
          - if @loops.any?
            %ul.collection
              - @loops.each do |loop_object|
                %li.collection-item.avatar
                  %a{ href: public_loop_path(loop_object.uuid), target: :blank }
                    %i.circle.material-icons.primary-color loop
                    %span.title= loop_object.name
                  %p.muted.hide-on-small-only
                    = pluralize(loop_object.dashboard_count, 'dashboard')
                  .secondary-content
                    - if loop_object.public_loop?
                      %a.modal-trigger{ href: "#speakeasy-loop-modal-#{loop_object.id}" }
                        %i.material-icons vpn_lock
                    %a.modal-trigger{ href: "#edit-loop-modal-#{loop_object.id}", class: 'green-text' }
                      %i.material-icons edit
                    = link_to loop_path(loop_object), method: :delete, class: 'red-text', data: { confirm: 'Are you sure?' } do
                      %i.material-icons delete
                = render partial: 'loops/edit', locals: { loop_object: loop_object, dashboards: @dashboards }
                - if loop_object.public_loop?
                  = render partial: 'loops/speakeasy', locals: { loop_object: loop_object}
          - else
            %p.flow-text You haven't created any loops.
= render partial: 'loops/new', locals: { loop_object: @loop, dashboards: @dashboards }

app/views/dashboards/show.html.haml
#version{ data: { version: ENV['APP_VERSION'] } }
#loop{ data: { dashboard_uuids: [@dashboard.uuid] } }
.row.dashboard-page
  = render @dashboard