config/routes.rb
Rails.application.routes.draw do
  default_url_options host: ENV["DOMAIN"]
  mount ActionCable.server => '/cable'

  # App Routes
  root to: 'dashboards#index'
  resources :dashboards,  except: [:new]
  resources :loops,       except: [:new, :edit]
  resources :connections, only:   [:show, :index, :create, :destroy], as: :integrations, controller: :integrations
  resources :glances,     except: [:new, :edit, :show, :index], as: :graphs, controller: :graphs
  resources :accounts,    except: [:edit]

  # Custom Routes and Actions
  patch '/dashboards/:id/duplicate'       => 'dashboards#duplicate',       as: :duplicate_dashboard
  patch '/dashboards/:id/reset-speakeasy' => 'dashboards#reset_speakeasy', as: :reset_dashboard_speakeasy
  patch '/loops/:id/reset-speakeasy'      => 'loops#reset_speakeasy',      as: :reset_loop_speakeasy
  patch '/glances/:id/reset-speakeasy'    => 'graphs#reset_speakeasy',     as: :reset_graph_speakeasy
  get   '/settings'                       => 'accounts#edit',              as: :settings
  get   '/billing'                        => 'accounts#billing',           as: :billing
  get   '/referral'                       => 'accounts#referral',          as: :referral
  post  '/stripe'                         => 'accounts#stripe'
  put   '/update-billing'                 => 'accounts#update_billing'
  get   '/signup(/:referrer_hash)'        => 'accounts#new',               as: :signup
  get   '/password'                       => 'accounts#password',          as: :password
  get   '/reset-password'                 => 'accounts#reset_password',    as: :reset_password
  post  '/password-auth'                  => 'accounts#password_auth'
  patch '/password-update'                => 'accounts#update_password'
  post  '/accounts'                       => 'accounts#create'
  get   '/login'                          => 'sessions#new',               as: :login
  post  '/login'                          => 'sessions#create'
  get   '/logout'                         => 'sessions#destroy',           as: :logout
  put   '/integrations/:id/autogenerate'  => 'integrations#autogenerate',  as: :autogenerate

  # Omniauth for Login
  get  'auth/:provider'          => 'sessions#create', as: :omniauth
  get  'auth/:provider/callback' => 'sessions#create'

  # Omniauth for Connections
  get  'integrations/:provider'          => 'integrations#create', as: :connection
  get  'integrations/:provider/callback' => 'integrations#create'

  # SpeakeasyLink Support
  get  '/board/:uuid' => 'dashboards#show',  as: :public_board
  get  '/loop/:uuid'  => 'loops#show',       as: :public_loop
  get  '/:uuid'       => 'graphs#edit',      as: :public_graph_form
  put  '/:uuid'       => 'graphs#update'

  # API and Webhook Routes
  namespace :api do
    namespace :zapier do
      resources :glances, only: [:index, :show], as: :graphs, controller: :graphs
      post 'glances/:id' => 'graphs#update'
    end
    namespace :hubspot do
      post :webhook, as: :graphs, controller: :graphs
    end
    namespace :google do
      post :webhook, as: :graphs, controller: :graphs
    end
  end
end

app/models/account.rb
class Account < ApplicationRecord
  has_secure_password
  acts_as_paranoid

  include AccountHelper
  include AccountOperation

  PERSONAS = [
    ['New Agent (0 to 2 years experience)',                   'persona_1'],
    ['Sophomore Agent (2 to 5 years experience)',             'persona_2'],
    ['Established Agent (6 or more years of experience)',     'persona_3'],
    ['New Team Owner (1 to 2 years owning your team)',        'persona_4'],
    ['Experienced Team Owner (more than 3 years experience)', 'persona_5']
  ]
  PLANS = {
    free:      { name: 'Free',   stripe_id: 0, price: 0  },
    agent:     { name: 'Agent',  stripe_id: 1, price: 9  },
    agentplus: { name: 'Agent+', stripe_id: 2, price: 49 },
    team:      { name: 'Team',   stripe_id: 3, price: 99 }
  }

  has_many :dashboards, dependent: :destroy
  has_many :loops, dependent: :destroy
  has_many :graphs, through: :dashboards
  has_many :integrations, dependent: :destroy
  has_many :referrals, foreign_key: :referrer_id, class_name: 'Account'

  belongs_to :referrer, counter_cache: :referrals_count, class_name: 'Account'

  before_create :generate_api_key
  after_create :seed_data
  after_create :new_account_jobs, :benefit_referrer, if: 'Rails.env.production?'
  after_update :increase_trial!
  after_update :update_zendesk!, :update_hubspot!, :update_stripe_plan, if: 'Rails.env.production?'

  validate  :email_uniqueness, on: :create
  validates :name, :email, presence: true, length: { maximum: 256 }
  validates :phone, length: { maximum: 30 }

  scope :valid, -> { where(billing_issue: false) }

  def self.from_omniauth(auth, opts)
    return false unless auth.present?
    expires = auth.credentials.expires_at.nil? ? '' : Time.at(auth.credentials.expires_at)
    account = with_deleted.where(provider: auth.provider, uid: auth.uid, email: auth.info.email).first_or_initialize(
      name:             auth.info.name,
      password:         SecureRandom.urlsafe_base64,
      oauth_token:      auth.credentials.token,
      oauth_expires_at: expires,
      source:           opts["state"].andand["source"],
      referrer_id:      opts["state"].andand["referrer"]
    )
    account.save if account.new_record?
    account
  end

  private

  def update_stripe_plan
    self.change_plan!(self.plan) if self.plan_changed?
  end

  def increase_trial!
    # Add a week to their customer's trial (or billing cycle) if they set their persona.
    self.add_week_to_billing_cycle! if self.persona_changed? and self.persona_was == nil
  end

  def generate_api_key
    self.api_token = loop do
      token = SecureRandom.hex
      break token unless Account.exists?(api_token: token)
    end
  end

  def benefit_referrer
    self.referrer.add_week_to_billing_cycle! unless self.referrer.nil?
  end

  def email_uniqueness
    if Account.with_deleted.exists?(email: email)
      errors.add(:email, "an account already exists with this email address")
    end
  end

  def seed_data
    seed_new_account(self.id)
  end

  def new_account_jobs
    AccountCreation.perform_in(1.second, self.id)
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  protect_from_forgery except: :stripe
  before_action :set_account, only: [:edit, :update, :update_billing, :billing]
  before_action :authorize, only: [:show, :edit, :update, :index, :destroy, :update_billing, :billing, :referral]

  def new
    @title    = 'Sign up'
    @source   = params[:s] || ''
    @account  = Account.new()
    @referrer = (params[:referrer_hash] && Base64.urlsafe_decode64(params[:referrer_hash])) || ''
  end

  def edit
    @title = 'Account Settings'
  end

  def billing
    @title = 'Account Billing'
  end

  def referral
    @title = 'Account Referral'
  end

  def update_billing
    current_account.update_columns(
      stripe_token: params[:stripe_token],
      cc_last_four: params[:cc_last_four]
    )
    @account.add_card!(params[:stripe_token])
    @account.update_billing_cycle!(@account.cycle_ends_on)
    redirect_back(fallback_location: settings_path(current_account), notice: 'New credit card added.')
  end

  def password
    redirect_to login_path if (current_account.nil? and params[:token].nil?)
    @account = current_account || Account.find_by(password_reset_token: params[:token])
    if ((@account.reset_password_date || DateTime.now) + 3.days) > DateTime.now.at_midnight
      @title = 'Change Password'
    else
      redirect_to login_path
    end
  end

  def reset_password
    @title = 'Reset Password'
  end

  def create
    @account = Account.new(account_params)
    @account.save ?
      (session[:account_id] = @account.id; redirect_to root_path(n: :t), notice: 'Welcome to AgentEcho!') :
      (render json: @account.errors, status: :unprocessable_entity)
  end

  def update
    @account.update(account_params) ?
      (redirect_back(fallback_location: settings_path(@accoaunt), notice: 'Account was successfully updated.')) :
      (render json: @account.errors, status: :unprocessable_entity)
  end

  def update_password
    redirect_to login_path if (current_account.nil? and params[:token].nil?)
    @account = current_account || Account.find_by(password_reset_token: params[:token])
    if @account.update(password: account_params[:password], password_confirmation: account_params[:password_confirmation])
      current_account.nil? ?
        (redirect_to login_path, notice: 'Password was updated') :
        (redirect_to settings_path(@account), notice: 'Password was updated')
    else
      render json: @account.errors, status: :unprocessable_entity
    end
  end

  def password_auth
    if(account = Account.find_by_email(params[:email]))
      account.reset_password!
      redirect_to login_path, notice: "Link to reset password was sent to #{account.email}"
    else
      render json: { email: ['not found'] }.to_json, status: :unprocessable_entity
    end
  end

  # Support actions
  def index
    @accounts = Account.all.order(:created_at).reverse
    super_account? ?
      (render) :
      (redirect_to logout_path)
  end

  def show
    super_account? ?
      (session[:account_id] = params[:id]; redirect_to root_path) :
      (redirect_to logout_path)
  end

  def destroy
    account = Account.find(params[:id])
    super_account? ?
      (account.destroy; redirect_to accounts_path, notice: "Account: '#{account.email}' was deleted.") :
      (redirect_to logout_path)
  end

  def stripe
    event_json = JSON.parse(request.body.read)
    account = Account.find(stripe_id: event_json['data']['object']['customer'])
    if event_json['type'] == 'charge.succeeded'
      subscription = account.stripe_subscription
      account.update_billing!(subscription.trial_end)
    elsif event_json['type'] == 'charge.failed'
      account.failed_billing!(event_json['data']['object']['failure_message'])
    end
    head :ok
  end

  private

  def super_account?
    [ 'ken@agentecho.io',
      'brian@agentecho.io',
      'rachel@agentecho.io'
    ].include?(current_account.email)
  end

  def set_account
    @account = current_account
  end

  def account_params
    params.require(:account).permit(
      :email,
      :password,
      :password_confirmation,
      :name,
      :phone,
      :time_zone,
      :email_optin,
      :source,
      :persona,
      :referrer_id,
      :plan
    )
  end
end

app/helpers/account_helper.rb
module AccountHelper
  def seed_new_account(account_id)
    account = Account.find(account_id)

    # Set end of cycle for trial
    account.update_columns(cycle_ends_on: (Time.current + 14.days).to_datetime)

    # Add Zapier Intergration
    IntegrationOperation.generate_zapier!(account)

    # Generating learning board
    dashboard = Dashboard.create(
      account: account,
      name: "Let's Learn 😊"
    )
    dashboard.graphs << Graph.new(size: 3, kind: 'native_number', title: 'This is a Number Glance', data: { output: 'number' })
  end
end

app/views/accounts/_form.html.haml
.input-field
  = f.text_field :name
  = f.label :name
.row
  .col.m8.s12.no-gutter
    .input-field
      = f.email_field :email
      = f.label :email
  .col.m4.s12
    .input-field
      = f.check_box :email_optin
      = f.label :email_optin, 'Recieve email updates?'
.input-field
  = f.phone_field :phone
  = f.label :phone

app/views/accounts/billing.html.haml
.row
  .col.m6.s12.offset-m3
    %h4
      Billing
      %small.right
        %a.dropdown-button{ data: { activates: "billing-dropdown", constrainwidth: false }, :href => "#" }
          %i.material-icons{ style: 'font-size: 2.5rem;' } arrow_drop_down_circle
    %hr
  .col.m6.s12.offset-m3.no-gutter
    .col.s12
      %blockquote.flow-text
        - if current_account.on_trial?
          Your trial ends on
          %strong= @account.cycle_ends_on.to_date.to_formatted_s(:long_ordinal)
          %br
        - else
          - if @account.billing_issue.present?
            Your subscription has a billing issue:
            %strong.red-text= @account.billing_issue_msg
            %br
          You will be charged
          %strong= @account.current_plan_price
          on
          %strong= @account.cycle_ends_on.to_date.to_formatted_s(:long_ordinal)
          - if @account.cc_last_four.present?
            %br
            Current Card Last Four Digits:
            %strong= @account.cc_last_four
      %br
      %h5 Change Plan
      %hr
      = form_for @account, remote: true do |f|
        %ul.collection
          %li.collection-item
            = f.radio_button :plan, :free, id: 'free-plan', class: 'with-gap plan'
            %label{ for: 'free-plan' } Free
            .right
              = link_to 'Learn More', '#', target: '_blank'
          %li.collection-item
            = f.radio_button :plan, :agent, id: 'agent-plan', class: 'with-gap plan'
            %label{ for: 'agent-plan' } Agent
            .right
              $9 / month &nbsp;
              = link_to 'Learn More', '#', target: '_blank'
          %li.collection-item
            = f.radio_button :plan, :agentplus, id: 'agent-plus-plan', disabled: true, class: 'with-gap plan'
            %label Agent+
            .right
              Coming Soon &nbsp;
              = link_to 'Learn More', '#', target: '_blank'
          %li.collection-item
            = f.radio_button :plan, :team, id: 'team-plan', disabled: true, class: 'with-gap plan'
            %label Team
            .right
              Coming Soon &nbsp;
              = link_to 'Learn More', '#', target: '_blank'
        = f.submit 'Change Plan', class: 'btn col s12 m6 offset-m3', id: 'update-plan', disabled: true
    = form_tag '/update-billing', id: 'payment-form', method: 'PUT' do
      .col.s12
        %br
        %h5 Update Credit Card
        %hr
      .col.s12
        .payment-errors.errors.card-panel.red.lighten-3.white-text.hide
          %div
      .input-field.col.s12
        %input{ data: { stripe: "number" }, size: "20", type: "number" }
        %label{ for: '1' } Card Number
      .input-field.col.s6
        %input{ data: { stripe: "exp_month" }, size: "2", type: "number" }
        %label{ for: '1' } Expiration Month (MM)
      .input-field.col.s6
        %input{ data: { stripe: "exp_year" }, size: "2", type: "number" }
        %label{ for: '1' } Expiration Year (YY)
      .input-field.col.s12
        %input{ data: { stripe: "cvc" }, size: "4", type: "number" }
        %label{ for: '1' } CVC Number
      .input-field.col.s12
        %input{ data: { stripe: "couponCode" }, type: "text" }
        %label{ for: '1' } Coupon Code
      .col.s12
        = submit_tag 'Update Credit Card', class: 'btn btn-large col s12'
%ul#billing-dropdown.dropdown-content
  %li= link_to 'Account', settings_path
  %li= link_to 'Password', password_path
  %li= link_to 'Referral', referral_path

:javascript
  $(document).on('change', '.plan', function () {
    $('#update-plan').attr('disabled', false)
  })

app/views/accounts/edit.html.haml
- cache [ApplicationHelper::APP_VERSION, @account] do
  .row
    .col.m6.s12.offset-m3
      %h4
        Edit Account
        %small.right
          %a.dropdown-button{ data: { activates: "account-dropdown", constrainwidth: false }, :href => "#" }
            %i.material-icons{ style: 'font-size: 2.5rem;' } arrow_drop_down_circle
      %hr
  .row
    .col.m6.s12.offset-m3
      = form_for @account, remote: true do |f|
        = render partial: 'partials/errors'
        = render 'form', f: f
        .input-field
          = f.select(:persona, Account::PERSONAS, include_blank: 'Persona', class: 'browser-default')
        .input-field
          = f.time_zone_select(:time_zone, ActiveSupport::TimeZone.us_zones, class: 'browser-default')
        .input-field
          = f.submit class: 'btn btn-large col s12'
%ul#account-dropdown.dropdown-content
  %li= link_to 'Billing', billing_path
  %li= link_to 'Password', password_path
  %li= link_to 'Referral', referral_path

app/views/accounts/index.html.haml
%table.highlight.bordered
  %thead
    %tr
      %th{"data-field" => "id"} ID
      %th{"data-field" => "name"} Name
      %th{"data-field" => "email"} Email
      %th{"data-field" => "phone"} Phone
      %th{"data-field" => "account-created"} Account Created
      %th{"data-field" => "last-login"} Last Login
      %th{"data-field" => "number-of-boards"} Number of Boards
      %th{"data-field" => "number-of-boards"} Referral Link
      %th{"data-field" => "number-of-boards"} Referrals Count
      %th
  %tbody
    - cache [ApplicationHelper::APP_VERSION, @accounts] do
      - @accounts.each do |account|
        - cache account do
          %tr
            %td= account.id
            %td= account.name
            %td= account.email
            %td= account.phone
            %td= account.created_at.to_formatted_s(:short)
            %td= account.last_login_at.to_formatted_s(:short)
            %td= account.dashboards.count
            %td= link_to signup_url(account.referral_code, host: 'app.agentecho.io'), target: :blank
            %td= account.referrals_count
            %td
              = link_to account_path(account) do
                %i.material-icons recent_actors
              = link_to account_path(account), method: :delete, class: 'red-text', data: { confirm: 'Are you sure you want to delete this account?' } do
                %i.material-icons delete

app/views/accounts/new.html.haml
.row
  .col.m6.s12.offset-m3
    %h4 New Account
    %hr
.row
  .col.m6.s12.offset-m3
    .row
      = link_to omniauth_path(provider: 'google', state: { source: @source, referrer: @referrer }) do
        .btn.btn-large.col.s12.white.black-text.omniauth-button
          = image_tag 'google-logo.png', class: 'left'
          .center
            Sign up With Google
    .row
      = link_to omniauth_path(provider: 'facebook', state: { source: @source, referrer: @referrer }) do
        .btn.btn-large.col.s12.white.black-text.omniauth-button
          = image_tag 'facebook-logo.png', class: 'left'
          .center
            Sign up With Facebook
    .section
      .row.center-align
        %h5 Or fill out this form
      .row
        = form_for @account, remote: true do |f|
          = render partial: 'partials/errors'
          = f.hidden_field :source, value: @source
          = f.hidden_field :referrer_id, value: @referrer
          = render 'form', f: f
          .input-field
            = f.password_field :password
            = f.label :password
          .input-field
            = f.password_field :password_confirmation
            = f.label :password_confirmation
          = f.submit 'Sign up', class: 'btn btn-large col s12'

app/views/accounts/password.html.haml
- cache [ApplicationHelper::APP_VERSION, @account] do
  .row
    .col.m6.s12.offset-m3
      %h4
        Change Password
        %small.right
          %a.dropdown-button{ data: { activates: "password-dropdown", constrainwidth: false }, :href => "#" }
            %i.material-icons{ style: 'font-size: 2.5rem;' } arrow_drop_down_circle
      %hr
  .row
    .col.m6.s12.offset-m3
      = form_for @account, url: { action: :update_password }, remote: true do |f|
        = hidden_field_tag :token, params[:token]
        = render partial: 'partials/errors'
        .input-field
          = f.password_field :password
          = f.label :password, 'New Password'
        .input-field
          = f.password_field :password_confirmation
          = f.label :password_confirmation
        = f.submit 'Update Password', class: 'btn btn-large col s12'
%ul#password-dropdown.dropdown-content
  %li= link_to 'Account', settings_path
  %li= link_to 'Billing', billing_path
  %li= link_to 'Referral', referral_path

app/views/accounts/referral.html.haml
.row
  .col.m6.s12.offset-m3
    %h4
      Referral
      %small.right
        %a.dropdown-button{ data: { activates: "billing-dropdown", constrainwidth: false }, :href => "#" }
          %i.material-icons{ style: 'font-size: 2.5rem;' } arrow_drop_down_circle
    %hr
  .col.m6.s12.offset-m3
    %blockquote.flow-text
      You have referred
      %strong
        = number_with_delimiter current_account.referrals_count
        = 'person'.pluralize(current_account.referrals_count)
    %p
      Share your referral link, every account that signs up using your link gets
      %strong
        %u you
      a free week of AgentEcho.
    .input-field.col.s12.m8.no-gutter
      %input.copy-source#referral_code{ disabled: true, type: "text", value: signup_url(current_account.referral_code, host: 'app.agentecho.io') }
      %label{ for: 'referral_code' } Referral Link
    .input-field.col.s12.m4
      %a.waves-effect.waves-light.btn.copy-btn.col.s12{ href: "#"}
        %i.material-icons.left content_copy
        Copy
    .col.s12.no-gutter
      %p Share on your social accounts for more free time with AgentEcho!
      %iframe{:allowtransparency => "true", :frameborder => "0", :height => "28", :scrolling => "no", :src => "https://www.facebook.com/plugins/share_button.php?href=#{URI::encode(signup_url(current_account.referral_code, host: 'app.agentecho.io'))}&layout=button&size=large&mobile_iframe=true&appId=845945175539314&width=73&height=28&quote=#{URI.encode('Checking out Agent Echo--create brilliant visual graphs with me, track your most important numbers!')}", :style => "border:none;overflow:hidden", :width => "73"}
      = link_to '', "https://twitter.com/intent/tweet?#{ { url: signup_url(current_account.referral_code, host: 'app.agentecho.io'), hashtags: 'AgentEcho', related: 'agentecho1', text: 'Checking out Agent Echo--create brilliant visual graphs with me, track your most important numbers!' }.to_query}", class: 'twitter-share-button', data: { size: 'large' }
%ul#billing-dropdown.dropdown-content
  %li= link_to 'Account', settings_path
  %li= link_to 'Billing', billing_path
  %li= link_to 'Password', password_path

%script{:src => "//platform.twitter.com/widgets.js"}

app/views/accounts/reset_password.html.haml
.row
  .col.m6.s12.offset-m3
    %h4 Reset Password
    %hr
  .col.m6.s12.offset-m3
    .row
      = form_tag '/password-auth', remote: true do |f|
        = render partial: 'partials/errors'
        %p Enter your email address here to have your password reset.
        .input-field
          = text_field_tag :email
          = label_tag :email
        = submit_tag 'Request Password Reset', class: 'btn btn-large col s12'